spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
  cloud:
    gateway:
      routes:
        - id: auth-service-fixed
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/profile, /auth/users/**
          filters:
            - AuthenticationFilter
        - id: auth-admin-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-admin/**
          filters:
            - AuthenticationFilter

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
