spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 1. Auth Service Routes
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        # 2. Delivery Service Routes
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/deliveries/**
          filters:
            - AuthenticationFilter

        # 3. Tracking Service Routes
        - id: tracking-service
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/tracking/**
          filters:
            - AuthenticationFilter

        # 4. Admin Service Routes
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970