spring:
  application:
    name: tracking-service

  datasource:
    url: jdbc:mysql://localhost:3306/tracking_db
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

file:
  upload-dir: C:\Users\Rishi Rao\IdeaProjects\SmartCourier\tracking-service\tracking-uploads\

server:
  port: 8083

